
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async validateMicrophone() : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_microphone") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startRecording() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopRecording() : Promise<Result<AudioResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getProjectContext(path: string | null) : Promise<Result<ProjectContext, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_project_context", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Shows a native OS popup context menu built from the given items.
 * 
 * Selection events are handled globally in lib.rs via `app.on_menu_event`,
 * which emits `context-menu-selected` to the frontend. This command only
 * builds the menu and calls popup_menu — no per-call listener is registered.
 */
async showContextMenu(items: ContextMenuItemDef[]) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_context_menu", { items }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openPreviewWindow(url: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_preview_window", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async closePreviewWindow() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_preview_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async injectInspector(enable: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("inject_inspector", { enable }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async applyCssChange(selector: string, property: string, value: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_css_change", { selector, property, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRunningAgents() : Promise<Result<AgentProcess[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_running_agents") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAgentMetrics(pid: number) : Promise<Result<AgentMetrics, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_agent_metrics", { pid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async captureRegion(x: number, y: number, width: number, height: number) : Promise<Result<CaptureResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("capture_region", { x, y, width, height }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getScreenInfo() : Promise<Result<ScreenInfo[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_screen_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openScreenshotOverlay() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_screenshot_overlay") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async closeScreenshotOverlay() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_screenshot_overlay") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async copyImageToClipboard(imageBase64: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("copy_image_to_clipboard", { imageBase64 }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async executeShell(command: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("execute_shell", { command }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openUrl(url: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_url", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getOpenWindows() : Promise<Result<WindowInfo[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_open_windows") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveSnapshot(name: string, windows: WindowInfo[]) : Promise<Result<WorkspaceSnapshot, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_snapshot", { name, windows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async restoreSnapshot(snapshot: WorkspaceSnapshot) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_snapshot", { snapshot }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkUpdate() : Promise<Result<UpdateInfo | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async installUpdate() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setDockPosition(x: number, y: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_dock_position", { x, y }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDockPosition() : Promise<Result<[number, number], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_dock_position") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleDockVisibility() : Promise<Result<boolean, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_dock_visibility") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setAlwaysOnTop(enabled: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_always_on_top", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AgentMetrics = { pid: number; log_lines: string[]; token_estimate: number | null; cost_estimate: number | null; log_path: string | null; metrics_available: boolean }
export type AgentProcess = { pid: number; name: string; agent_type: string; cmd: string[]; cwd: string | null; memory_kb: number; cpu_percent: number; start_time: number; status: string }
export type AppError = { Window: string } | { Shell: string } | { Io: string } | { Screenshot: string } | { Audio: string } | { Process: string } | { Updater: string }
export type AudioResult = { wav_base64: string; duration_seconds: number; sample_rate: number }
export type CaptureResult = { image_base64: string; width: number; height: number; x: number; y: number }
export type ContextMenuItemDef = { id: string; label: string; separator: boolean }
export type PackageInfo = { name: string; version: string; description: string | null; main_dependencies: string[] }
export type ProjectContext = { git_root: string | null; project_name: string | null; package_json: PackageInfo | null; recent_commits: string[]; current_branch: string | null }
export type ScreenInfo = { id: number; x: number; y: number; width: number; height: number; scale_factor: number }
export type UpdateInfo = { version: string; body: string }
export type WindowInfo = { app_name: string; title: string; x: number; y: number; width: number; height: number }
export type WorkspaceSnapshot = { id: string; name: string; created_at: number; windows: WindowInfo[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
