import { Short } from './models/short.model';

export const SHORTS_CATALOG: readonly Short[] = [
  {
    id: 'ps-1',
    title: 'Write Better Prompts in 60s',
    description: 'The STAR framework for AI prompts: Situation, Task, Action, Result.',
    url: 'https://www.youtube.com/watch?v=jC4v5AS4RIM',
    category: 'prompt-engineering',
    durationSeconds: 58,
    tags: ['prompts', 'claude', 'framework'],
  },
  {
    id: 'ps-2',
    title: 'Claude Code: Slash Commands',
    description: 'Speed up your workflow with /clear, /compact, and custom slash commands.',
    url: 'https://www.youtube.com/watch?v=s0jQKsrOSuU',
    category: 'shortcuts',
    durationSeconds: 45,
    tags: ['claude-code', 'shortcuts'],
  },
  {
    id: 'ps-3',
    title: 'Tauri v2 Crash Course',
    description: 'Build cross-platform desktop apps with Tauri v2 and Rust.',
    url: 'https://www.youtube.com/watch?v=G8-M7EKFpfI',
    category: 'agent-usage',
    durationSeconds: 52,
    tags: ['tauri', 'rust', 'desktop'],
  },
  {
    id: 'ps-4',
    title: 'Angular Signals in 60s',
    description: 'Reactive state with Angular Signals: signal(), computed(), effect().',
    url: 'https://www.youtube.com/watch?v=oqYQG7QMdzw',
    category: 'prompt-engineering',
    durationSeconds: 60,
    tags: ['angular', 'signals', 'reactive'],
  },
  {
    id: 'ps-5',
    title: 'Cursor: Multi-File Edits',
    description: 'Use @ to reference files and apply bulk edits across your codebase.',
    url: 'https://www.youtube.com/watch?v=yk9lXobkmHE',
    category: 'agent-usage',
    durationSeconds: 55,
    tags: ['cursor', 'editing'],
  },
  {
    id: 'ps-6',
    title: 'Aider: Best Commit Workflow',
    description: 'Auto-commit with --auto-commits and review with git diff.',
    url: 'https://www.youtube.com/watch?v=MPYFPvxfGZs',
    category: 'agent-usage',
    durationSeconds: 48,
    tags: ['aider', 'git'],
  },
  {
    id: 'ps-7',
    title: 'Rust Error Handling Patterns',
    description: 'Result, Option, thiserror and anyhow — the right tool for each case.',
    url: 'https://www.youtube.com/watch?v=jpOHFO9hBFE',
    category: 'debugging',
    durationSeconds: 40,
    tags: ['rust', 'errors', 'result'],
  },
  {
    id: 'ps-8',
    title: 'AI Pair Programming Tips',
    description: 'How to get 10x more from your AI coding assistant with context and intent.',
    url: 'https://www.youtube.com/watch?v=xBiGteL9Lvo',
    category: 'prompt-engineering',
    durationSeconds: 62,
    tags: ['ai', 'workflow', 'tips'],
  },
];
