import { Short } from './models/short.model';

export const SHORTS_CATALOG: readonly Short[] = [
  {
    id: 'ps-1',
    title: 'Write Better Prompts in 60s',
    description: 'The STAR framework for AI prompts: Situation, Task, Action, Result.',
    url: 'https://www.youtube.com/shorts/dQw4w9WgXcQ',
    category: 'prompt-engineering',
    durationSeconds: 58,
    tags: ['prompts', 'claude', 'framework'],
  },
  {
    id: 'ps-2',
    title: 'Claude Code: Slash Commands',
    description: 'Speed up your workflow with /clear, /compact, and custom slash commands.',
    url: 'https://www.youtube.com/shorts/dQw4w9WgXcQ',
    category: 'shortcuts',
    durationSeconds: 45,
    tags: ['claude-code', 'shortcuts'],
  },
  {
    id: 'ps-3',
    title: 'Multi-Agent Debugging',
    description: 'How to use parallel agents to debug faster.',
    url: 'https://www.youtube.com/shorts/dQw4w9WgXcQ',
    category: 'agent-usage',
    durationSeconds: 52,
    tags: ['agents', 'debugging', 'parallel'],
  },
  {
    id: 'ps-4',
    title: 'Context Window Tips',
    description: 'Keep Claude focused: /compact, targeted reads, avoid dumping logs.',
    url: 'https://www.youtube.com/shorts/dQw4w9WgXcQ',
    category: 'prompt-engineering',
    durationSeconds: 60,
    tags: ['context', 'claude', 'tips'],
  },
  {
    id: 'ps-5',
    title: 'Cursor: Multi-File Edits',
    description: 'Use @ to reference files and apply bulk edits across your codebase.',
    url: 'https://www.youtube.com/shorts/dQw4w9WgXcQ',
    category: 'agent-usage',
    durationSeconds: 55,
    tags: ['cursor', 'editing'],
  },
  {
    id: 'ps-6',
    title: 'Aider: Best Commit Workflow',
    description: 'Auto-commit with --auto-commits and review with git diff.',
    url: 'https://www.youtube.com/shorts/dQw4w9WgXcQ',
    category: 'agent-usage',
    durationSeconds: 48,
    tags: ['aider', 'git'],
  },
  {
    id: 'ps-7',
    title: 'Debugging with AI: Read First',
    description: 'Always read the error, trace the stack, then ask — never paste blindly.',
    url: 'https://www.youtube.com/shorts/dQw4w9WgXcQ',
    category: 'debugging',
    durationSeconds: 40,
    tags: ['debugging', 'workflow'],
  },
  {
    id: 'ps-8',
    title: 'System Prompt Secrets',
    description: 'How project-level CLAUDE.md shapes AI behavior across sessions.',
    url: 'https://www.youtube.com/shorts/dQw4w9WgXcQ',
    category: 'prompt-engineering',
    durationSeconds: 62,
    tags: ['claude', 'system-prompt'],
  },
];
